### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by jars99** [chocolatey-archive/puppet-chocolatey-handsonlab#1]
It looks like there might be some files missing from the lab.  

I cloned the repo, installed the vagrant 1.2.7, and installed the plugin.  

I then ran "vagrant up".  It downloaded the vm image, but then thew a couple errors:

:~/git/puppet-chocolatey-handsonlab/Lab1$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Box 'win7x64pro' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading or copying the box...
Extracting box...te: 3082k/s, Estimated time remaining: 0:00:01)
Successfully added box 'win7x64pro' with provider 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
- The host path of the shared folder is missing: puppet/box_modules

puppet provisioner:
- The configured module path doesn't exist: /home/jbristow/git/puppet-chocolatey-handsonlab/Lab1/puppet/modules

**Comment by jars99** [comment]
The fix was just to create the two missing folders (modules and box_modules) in the puppet directory.  

I'm guessing you can't add these folders to the github repo because git doesn't like empty folders?

**Comment by ferventcoder** [comment]
This is correct.

**Comment by jars99** [comment]
Next problem: 
[default] Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/i18n-0.6.4/lib/i18n/interpolate/ruby.rb:24:in `block in interpolate_hash': missing interpolation argument :command in "An error occurred executing a remote WinRM command.\n\nShell: %{shell}\nCommand: %{command}\nMessage: %{message}" ({:_key=>:winrm_execution_error, :_namespace=>"vagrant_windows.errors", :shell=>:powershell, :message=>"No such file or directory - shell/main.cmd"} given) (I18n::MissingInterpolationArgument)

Edit: I forgot to change back to the Lab1 directory after creating the other 2 directories, and then got the above error because it couldn't find the path to the "shell" directory.

**Comment by jars99** [comment]
I believe you can touch a "." file in each of the empty directories and check them in to git.  That way, users won't have to create the directories themselves.

**Comment by ferventcoder** [comment]
Good point. I might do that...

**Comment by ferventcoder** [comment]
Fixed in fc2e52477d5a20eaeeed2b8215f27616e85e609c
