### ISSUE TITLE
You must provide a value expression on the right-hand side of the '-and' operator.

### ISSUE THREAD

**Issue by jars99** [chocolatey-archive/puppet-chocolatey-handsonlab#2]
I'm stuck again:

[default] Running provisioner: shell...

C:\Users\vagrant>
echo 'Ensuring .NET 4.0 is installed' 
'Ensuring .NET 4.0 is installed'
Creating folder 'c:\vagrant\resources\NetFx4'
Downloading 'http://download.microsoft.com/download/5/6/2/562A10F9-C9F4-4313-A044-9C94E0A8FAC8/dotNetFx40_Client_x86_x64.exe' to 'c:\vagrant\resources\NetFx4\dotNetFx40.exe'
Installing 'c:\vagrant\resources\NetFx4\dotNetFx40.exe'

C:\Users\vagrant>echo 'Ensuring Chocolatey is Installed' 
'Ensuring Chocolatey is Installed'
You must provide a value expression on the right-hand side of the '-and' operat
or.

When I try to run the InstallChocolatey.ps1 script manually, I get a bit more info:

You must provide a value expression on the right-hand side of the '-and' operat
or.
At C:\vagrant\shell\InstallChocolatey.ps1:28 char:33
- if ($chocoPkgFile -ne $null -and <<<<  Test-Path $chocoPkgFile) {
  - CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
    ception
  - FullyQualifiedErrorId : ExpectedValueExpressionjbristow@kaos:~/git/puppet-chocolatey-handsonlab/Lab1/shell$ 

I know nothing of Powershell scripts, but it looks like there's an operator on the right hand side to me...

**Comment by ferventcoder** [comment]
grab latest, is that still there? 
Just remove the `-and Test-Path $chocoPkgFile` from that line.

**Comment by ferventcoder** [comment]
I just fixed and pushed this

**Comment by ferventcoder** [comment]
Fixed in 72295e1db1aeed4be6f8a2808e370ef84a7317e1
