### ISSUE TITLE
problems with warmup

### ISSUE THREAD

**Issue by jars99** [chocolatey-archive/puppet-chocolatey-handsonlab#3]
We're doing good - moving along to the next one:

There's no "warmup" package in the resources directory

When I just remove the "source" line, it downloads and installs from the Internet.  I verified that it installed by looking in the c:\chocolatey\lib directory.

However, it doesn't seem to be working correctly.    After creating c:\temp and cd'ing there, I run "warmup chocolatey mypkg".  There's no output, and no directory created.  

I looked at info on the package, and it says it is supposed to create a c:\nuget folder.  No such folder is there.

**Comment by ferventcoder** [comment]
Yup, that's part of the lab. To see that you don't need a source line. Can you verify that you have a `c:\code\_templates\chocolatey` folder?

**Comment by ferventcoder** [comment]
Fixed documentation for warmup package - 0fec4c6c005d77196afd9001643637ff9b38cfc1

**Comment by jars99** [comment]
Yes, that folder is there.

**Comment by ferventcoder** [comment]
And when you run `warmup chocolatey mypkg` in the vm nothing happens?

**Comment by jars99** [comment]
When I try running the command directly on the box, this error pops up:
![dotneterror](https://f.cloud.github.com/assets/4067216/1086064/40dbf43c-15ef-11e3-9ee8-aceb91bbdf52.png)

And of course clicking "yes" does nothing

**Comment by jars99** [comment]
I thought .Net 4.0 was installed earlier on in the process, but just in case I tried installing it with chocolatey: `cinst dotnet4.0`.  It wasn't exactly clean (It threw an error about needing to reboot to rollback changes), but it did eventually install, and I rebooted.  

Now when I run `warmup chocolatey mypkg` I get an unhandled exception.  It says "Could not find a part of the path 'C:\CODE_templates\chocolatey`."

If I cd to c:\code and do a `dir` I can see the _templates folder (which is listed as a symlink).  If I try to `cd` into the folder, I get this error:
"The system cannot find the path specified."

Also, the mypkg folder did get created - but there's nothing in it.

**Comment by ferventcoder** [comment]
Ah yes, another step in the docs I need!

Yes it was installed but the system needs a reboot before it can run
executables. Weird I know that choco does fine.

On Thursday, September 5, 2013, Jared Bristow wrote:

> When I try running the command directly on the box, this error pops up:
> [image: dotneterror]https://f.cloud.github.com/assets/4067216/1086064/40dbf43c-15ef-11e3-9ee8-aceb91bbdf52.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chocolatey/puppet-chocolatey-handsonlab/issues/3#issuecomment-23845235
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Okay that's weird. The folder mount was working but let me see what I can
do later today.

On Thursday, September 5, 2013, Jared Bristow wrote:

> I thought .Net 4.0 was installed earlier on in the process, but just in
> case I tried installing it with chocolatey: cinst dotnet4.0. It wasn't
> exactly clean (It threw an error about needing to reboot to rollback
> changes), but it did eventually install, and I rebooted.
> 
> Now when I run warmup chocolatey mypkg I get an unhandled exception. It
> says "Could not find a part of the path 'C:\CODE_templates\chocolatey`."
> 
> If I cd to c:\code and do a dir I can see the _templates folder (which is
> listed as a symlink). If I try to cd into the folder, I get this error:
> "The system cannot find the path specified."
> 
> Also, the mypkg folder did get created - but there's nothing in it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/chocolatey/puppet-chocolatey-handsonlab/issues/3#issuecomment-23846436
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by jars99** [comment]
The docs do say to reboot, and I had rebooted, but it still thought .Net 4.0 wasn't installed.  Why would it think that?  Wasn't it already installed by the main.cmd script?  Does installing dotnet4.0 through chocolatey install something different?

**Comment by ferventcoder** [comment]
Any progress?

**Comment by jars99** [comment]
No - I even tried deleting the VM and starting over from scratch.  Still had the same issues.  
Did you figure anything out about the symlink?

**Comment by ferventcoder** [comment]
Did we change the folder over to c:_templates? The folder of c:\code would be shared and thus a symlink wouldn't work there.

**Comment by ferventcoder** [comment]
I'm going to close this pending new comments.
