### ISSUE TITLE
dotnet install not complete

### ISSUE THREAD

**Issue by cdenneen** [chocolatey-archive/puppet-chocolatey-handsonlab#5]
So I've used the dot net install ps1 in another Vagrantfile and then actually used the complete Lab1 and no matter what after Net 4.0 installs successfully the cinst command will fail with "Execution of NuGet not detected. Please make sure you have .NET Framework 4.0 installed and are passing arguments to the install command."

I have confirmed that if I go into gui, open control panel and programs and run repair on the .NET Client install everything starts to work. I just don't get the difference between me running repair through gui and /repair flag sent to installer

Here is the output of the run:

```
$ vagrant up                                                                                             [1.9.3]
WARNING: Could not load IOV methods. Check your GSSAPI C library for an update
WARNING: Could not load AEAD methods. Check your GSSAPI C library for an update
WARNING: Nokogiri was built against LibXML version 2.8.0, but has dynamically loaded 2.9.1
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'windows-server-2008-r2-eval'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: Lab1_default_1396622969283_50281
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5985 => 5985 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/chris/src/lab/Lab1
    default: /_templates => /Users/chris/src/lab/Lab1/resources/templates/_templates
    default: /tmp/vagrant-puppet-1/modules-0 => /Users/chris/src/lab/Lab1/puppet/modules
    default: /tmp/vagrant-puppet-1/manifests => /Users/chris/src/lab/Lab1/puppet/manifests
    default: /ProgramData/PuppetLabs/puppet/etc/modules => /Users/chris/src/lab/Lab1/puppet/box_modules
==> default: Running provisioner: shell...

C:\Users\vagrant>echo 'Ensuring .NET 4.0 is installed'
'Ensuring .NET 4.0 is installed'
Creating folder 'c:\vagrant\resources\NetFx4'
Downloading 'http://download.microsoft.com/download/5/6/2/562A10F9-C9F4-4313-A044-9C94E0A8FAC8/dotNetFx40_Client_x86_x64.exe' to 'c:\vagrant\resources\NetFx4\dotNetFx40.exe'
Installing 'c:\vagrant\resources\NetFx4\dotNetFx40.exe'

C:\Users\vagrant>echo 'Ensuring Chocolatey is Installed'
'Ensuring Chocolatey is Installed'
PATH environment variable does not have 'C:\Chocolatey\bin' in it. Adding...

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----          4/4/2014  10:53 AM            chocInstall
Downloading http://chocolatey.org/api/v2/package/chocolatey/ to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip
Download 7Zip commandline tool
Downloading http://chocolatey.org/7za.exe to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\7za.exe
Extracting C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as a User Environment variable and setting it to 'C:\Chocolatey'
We are setting up the Chocolatey repository for NuGet packages that should be at the machine level. Think executables/application packages, not library packages.
That is what Chocolatey NuGet goodness is for. The repository is set up at 'C:\Chocolatey'.
The packages themselves go to 'C:\Chocolatey\lib' (i.e. C:\Chocolatey\lib\yourPackageName).
A batch file for the command line goes to 'C:\Chocolatey\bin' and points to an executable in 'C:\Chocolatey\lib\yourPackageName'.

Creating Chocolatey NuGet folders if they do not already exist.

d----          4/4/2014  10:53 AM            bin
d----          4/4/2014  10:53 AM            lib
d----          4/4/2014  10:53 AM            chocolateyinstall
Copying the contents of 'C:\Users\vagrant\AppData\Local\Temp\chocolatey\chocInstall\tools\chocolateyInstall' to 'C:\Chocolatey'.
Creating 'C:\Chocolatey\bin\chocolatey.bat' so you can call 'chocolatey'.
Creating 'C:\Chocolatey\bin\choco.bat' so you can call 'choco'.
Creating 'C:\Chocolatey\bin\cinst.bat' so you can call 'choco install' from a shortcut of 'cinst'.
Creating 'C:\Chocolatey\bin\cup.bat' so you can call 'choco update' from a shortcut of 'cup'.
Creating 'C:\Chocolatey\bin\cuninst.bat' so you can call 'choco uninstall' from a shortcut of 'cuninst'.
Creating 'C:\Chocolatey\bin\clist.bat' so you can call 'choco list' from a shortcut of 'clist'.
Creating 'C:\Chocolatey\bin\cver.bat' so you can call 'choco version' from a shortcut of 'cver'.
Creating 'C:\Chocolatey\bin\cpack.bat' so you can call 'choco pack' from a shortcut of 'cpack'.
Creating 'C:\Chocolatey\bin\cpush.bat' so you can call 'choco push' from a shortcut of 'cpush'.
User PATH already contains either 'C:\Chocolatey\bin' or '%DIR%..\bin'
Processing choco.bat to make it portable
Processing chocolatey.bat to make it portable
Processing cinst.bat to make it portable
Processing clist.bat to make it portable
Processing cpack.bat to make it portable
Processing cpush.bat to make it portable
Processing cuninst.bat to make it portable
Processing cup.bat to make it portable
Processing cver.bat to make it portable
Chocolatey is now ready.
You can call chocolatey from anywhere, command line or powershell by typing chocolatey.
Run chocolatey /? for a list of functions.
You may need to shut down and restart powershell and/or consoles first prior to using chocolatey.
If you are upgrading chocolatey from an older version (prior to 0.9.8.15) and don't use a custom chocolatey path, please find and delete the C:\NuGet folder after verifying that C:\Chocolatey has the same contents (minus chocolateyinstall of course).
Ensuring chocolatey commands are on the path
Chocolatey (v0.9.8.23) is installing 'chocolatey' and dependencies. By installing you accept the license for 'chocolatey' and each dependency you are installing.
Execution of NuGet not detected. Please make sure you have .NET Framework 4.0 installed and are passing arguments to the install command.
Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: chocolatey
Reading environment variables from registry. Please wait... Done.



C:\Users\vagrant>echo 'Install puppet if missing'
'Install puppet if missing'
Chocolatey (v0.9.8.23) is installing 'puppet' and dependencies. By installing you accept the license for 'puppet' and each dependency you are installing.
Execution of NuGet not detected. Please make sure you have .NET Framework 4.0 installed and are passing arguments to the install command.
Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: puppet
Reading environment variables from registry. Please wait... Done.

C:\Users\vagrant>SET PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Puppet Labs\Puppet\bin;C:\Program Files (x86)\Puppet Labs\Puppet\bin;C:\Program Files\Puppet Labs\Puppet\bin;

C:\Users\vagrant>echo "Ensuring environment for puppet"
"Ensuring environment for puppet"

C:\Users\vagrant>call environment.bat
'Install Required libraries for puppet if missing'
Ensuring librarian puppet
Installing librarian puppet
Successfully installed thor-0.19.1
Successfully installed highline-1.6.21
Successfully installed librarian-0.1.2
Successfully installed librarian-puppet-0.9.17
4 gems installed
Running librarian-puppet install --clean
cannot find git
==> default: Running provisioner: puppet...
Running Puppet with /tmp/vagrant-puppet-1/manifests/site.pp...
Notice: Compiled catalog for win-hnb91nnab2g.local in environment production in 0.41 seconds
Error: Parameter provider failed on Package[roundhouse]: Invalid package provider 'chocolatey' at C:/tmp/vagrant-puppet-1/manifests/site.pp:5
Wrapped exception:
Invalid package provider 'chocolatey'
An error occurred executing a remote WinRM command.

Shell: powershell
Command: $env:FACTER_domain='local'; $env:FACTER_kernel='windows'; $env:FACTER_operatingsystem='windows'; $env:FACTER_osfamily='windows';  puppet apply --modulepath '/ProgramData/PuppetLabs/puppet/etc/modules;/tmp/vagrant-puppet-1/modules-0' --manifestdir /tmp/vagrant-puppet-1/manifests --detailed-exitcodes /tmp/vagrant-puppet-1/manifests/site.pp
Message: Puppet failed with an exit code of 1
```

**Comment by ferventcoder** [comment]
It's likely a pending reboot issue. I don't run into it very often with .net framework install but sometimes it refuses to run apps until the server gets rebooted.

**Comment by ferventcoder** [comment]
Oh wait, looks like there is another issue in here as well:

```
Running librarian-puppet install --clean
cannot find git
```

and then

```
Notice: Compiled catalog for win-hnb91nnab2g.local in environment production in 0.41 seconds
Error: Parameter provider failed on Package[roundhouse]: Invalid package provider 'chocolatey' at C:/tmp/vagrant-puppet-1/manifests/site.pp:5
Wrapped exception:
Invalid package provider 'chocolatey'
```

**Comment by ferventcoder** [comment]
The fix for this is to take a look at what is being done here: https://github.com/ferventcoder/vagrant-windows-puppet

**Comment by ferventcoder** [comment]
Most specifically https://github.com/ferventcoder/vagrant-windows-puppet/blob/master/boxes/shared/shell/InstallPuppetFromMSI.ps1 - This is a better way to go about getting puppet installed during the vagrant bootstrapping, it's based on the work I provided to puppet-bootstrap https://github.com/hashicorp/puppet-bootstrap/pull/18

**Comment by cdenneen** [comment]
thanks... I'll try to reboot the box and run provision again but is there a way to automate the reboot during the provision? seems like there needs to be a way to reboot the node so the config can finish cleanly without erroring

Also puppet is installed on my basebox git isn't so that's why the librarian is failing... once i get chocolatey working I can have that install git before librarian-puppet.

**Comment by cdenneen** [comment]
OK so i've used my basebox and your basebox and for some reason your basebox of win2008 works with the .NET install errors for cinst whereas mine doesn't. This really puzzles me unless there was some additional magic done to your basebox before packaging that I didn't do.
Do you have any specific steps you used besides recommendations of having git/bitvise installed?

**Comment by ferventcoder** [comment]
Ah, ya. The basebox is built based on WinRb/vagrant-windows specifications
and has other improvements - see
https://vagrantcloud.com/ferventcoder/win2008r2-x64-nocm for specific
details about installs and preconfiguration.

On Friday, April 4, 2014, cdenneen notifications@github.com wrote:

> OK so i've used my basebox and your basebox and for some reason your
> basebox of win2008 works with the .NET install errors for cinst whereas
> mine doesn't. This really puzzles me unless there was some additional magic
> done to your basebox before packaging that I didn't do.
> Do you have any specific steps you used besides recommendations of having
> git/bitvise installed?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/chocolatey/puppet-chocolatey-handsonlab/issues/5#issuecomment-39606308
> .

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by cdenneen** [comment]
OK so the process in which I setup the original base box is very similar (http://www.thomasvjames.com/2013/09/create-a-windows-base-box-for-vagrant/) it does all the WinRb steps and I've reviewed your specific details. I didn't see anything honestly different. Only difference I saw was downloading that VHD file was build 7600 and yours uses 7601 (SP1) so by chance I figured maybe it was SP1 that was the reason why it worked on your basebox and not mine. I've since rebuilt the basebox following the link here and applied SP1 but still same issue about NuGet. I've even tried to build a completely fresh basebox from SP1 media just in case it was something with the eval image I was using.
Only difference I can see at this point are as follows:
- I did not install any of your pre-installed software except Guest Additions
- I've not sure the 30 services you left running so I just made sure the ones enabled in WinRb were running
- I didn't enable autologin (curious if/how this could be it)

I'm really stumped as to what might be causing this.
I've tried the reboot method but only thing that seems to fix it is if I click Repair for .NET under Programs and Features in the UI and then run `vagrant provision`

I have uploaded my setup to a repository (**basebox URL updated**) if someone could help me understand why the NuGet error keeps happening with all my baseboxes but not the win2008r2-x64-nocm provided by @ferventcoder (I've switched between the boxes so I know it's not the Vagrantfile). Seems like I'm missing something majorly fundamental in order to create any sort of basebox.

https://github.com/cdenneen/vagrant-windows-build

```
==> default: Running provisioner: shell...
Chocolatey (v0.9.8.23) is installing 'git' and dependencies. By installing you accept the license for 'git' and each dependency you are installing.
Execution of NuGet not detected. Please make sure you have .NET Framework 4.0 installed and are passing arguments to the install command.
Chocolatey (v0.9.8.23) is installing 'puppet' and dependencies. By installing you accept the license for 'puppet' and each dependency you are installing.
Execution of NuGet not detected. Please make sure you have .NET Framework 4.0 installed and are passing arguments to the install command.
Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: git, puppet
Reading environment variables from registry. Please wait... Done.
An error occurred executing a remote WinRM command.

Shell: powershell
Command:               $old = Get-ExecutionPolicy;
              Set-ExecutionPolicy Unrestricted -force;
              c:\tmp\vagrant-shell.ps1;
              Set-ExecutionPolicy $old -force

Message: Command execution failed with an exit code of 1
```

**Comment by ferventcoder** [comment]
It's not autologin. It might have to do with Git being installed and all msys tools being on the path, but I doubt that for some reason. It's hard to say exactly what could be causing the issue, but the issue isn't really an issue with this hands on lab. I would suggest raising it somewhere else (perhaps a mailing list), although I'm not really sure where it could be raised.

As I think about it, check to see if Windows Updates is turned on or off. With it turned on it may flag the registry for a reboot (since .net fx is a KB).

**Comment by cdenneen** [comment]
I'm curious if its actually using vagrant ssh instead of winrm in your basebox and that's why the .NET install is completing without need of a repair. I'm not sure if @mitchellh, @WinRb, @sneal would be helpful since it seems to be a vagrant/winrm bug rather than a chocolatey issue.

**Comment by ferventcoder** [comment]
I don't think it has to do with a bug on those things. Try this: shut off and disable windows update services on your basebox. Then try it. If that is not it, move to the next service that is different between your box and mine.

**Comment by cdenneen** [comment]
Thanks definitely not Windows Update as that's disabled in the base_setup.ps1. Hopefully the mentions here will get some insight from the correct party and lead me to where to properly raise this.

**Comment by cdenneen** [comment]
@ferventcoder ok thanks... i can try disabling/enabling services

**Comment by ferventcoder** [comment]
And yours is R2, correct?

**Comment by cdenneen** [comment]
yep... in Vagrantfile i have URLs to my first which is R2 with SP1 manually added and the current which was a R2 base with SP1 (didn't need SP1 added manually) cdenneen/vagrant-windows-build

**Comment by ferventcoder** [comment]
I'd be interested to know what you come up with, as the need for the reboot can get particularly annoying at times when it does pop up.

**Comment by cdenneen** [comment]
yeah reboot doesn't help... if I repair through Program Uninstall then provision works... and oddly if i uninstall .NET and run the setup_requirements.cmd (that vagrant shell runs as first provision step) through the GUI I am able to provision.
So it seems there is something fundamentally different between running setup_requirements.cmd via Vagrantfile and through GUI... which is why I was thinking its a possible winrm bug that you weren't seeing because you configured your basebox to use vagrant ssh. (I know I'm grasping here but I've tried to provide everything in that repo to help someone with more experience provide some better insight into what I may have missed). As far as I can tell the WinRM service is running, settings are configured via Vagrantfile, firewall is off, UAC is off... just doesn't make sense.

**Comment by ferventcoder** [comment]
Ah, so you are stating that the install must be repaired. Yeah, that could be a problem with some version of vagrant and/or vagrant-windows that you are using. What kind of box is your host? and what versions of those?

**Comment by cdenneen** [comment]
Host - OSX 10.9
Virtualbox - 4.3.10
Virtualbox Additions - 4.3.10
Vagrant - 1.5.2
Vagrant-Windows - 1.6.0

**Comment by cdenneen** [comment]
But if it was my "setup" I'm going to guess it wouldn't be successful with your basebox and not mine... so there is definitely something missing in my base_setup.ps1 to get winrm to work properly for not needing a repair after .NET install or it's vagrant-windows(winrm) bug that  you don't experience because your's using vagrant ssh instead of winrm?

**Comment by ferventcoder** [comment]
Good point. You built your basebox with virtualbox 4.3.10 or an earlier version?

**Comment by ferventcoder** [comment]
Mine uses winrm I believe. The ssh calls come later when you `vagrant ssh` from the command line.

**Comment by cdenneen** [comment]
4.3.10

**Comment by ferventcoder** [comment]
Otherwise the shell provisioner's communication method is overridden to `winrm` instead of the default `ssh`.

**Comment by ferventcoder** [comment]
So we have a thought that it might be related to UAC.
